DROP TABLE IF EXISTS GYMUSER;

CREATE TABLE GYMUSER(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255), SOBRENOME VARCHAR(255), SEXO VARCHAR(255), DATEBIRTH VARCHAR(255), EMAIL VARCHAR(255), CPF VARCHAR(255), SENHA VARCHAR(255))